version: "3"
services:
  samba:
    image: dperson/samba
    tty: true
    container_name: samba
    environment:
      - TZ=EST5EDT
    ports:
      - 139:139
      - 445:445
    command: '-s "Mount;/mnt" -s "xpto volume;/mnt2;yes;no;no;xpto" -u "xpto;bobspasswd" -p'
    volumes:
      - ./private:/mnt2:z
      - ./public:/mnt:z
